### ISSUE TITLE
Header height changes with window width

### ISSUE THREAD

**Issue by MakisH** [precice/run.precice-frontend#8]
A minor CSS issue: for some (small) window widths, the height of the header changes, causing some elements to overlap. Check screenshot!

![squeezed](https://user-images.githubusercontent.com/4943683/45809485-94c1a580-bcc8-11e8-8a0c-18bfc7172108.png)

**Comment by shkodm** [comment]
@MakisH, I believe this is just because of the the side menu button. It is ```positition: fixed``` , so it is always on top even if scroll down (mostly useful on the landing page), so it might overlap during resizing. Rest of elements are using flexbox, so they will not overlap during resizing. 

I will fix it by altering CSS  of menu button later on today.

**Comment by MakisH** [comment]
No hurry, I just wanted to document this! :)

**Comment by shkodm** [comment]
@MakisH , can you check it if this works for you ? I tested on my machine with different window sizes, zooming in - out, and it looks fine.

**Comment by MakisH** [comment]
Looks fixed! Thanks for the super fast debugging! :D
